# Generated by Django 4.2.9 on 2024-03-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_galeria_options_alter_parceiros_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OndeComprar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(db_column='Cidade', max_length=50)),
                ('estado', models.CharField(db_column='Estado', max_length=2)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=25, null=True)),
                ('cel', models.CharField(db_column='Cel', max_length=25)),
                ('enderecomaps', models.CharField(blank=True, db_column='EnderecoMaps', max_length=255, null=True)),
            ],
        ),
    ]
