# Generated by Django 4.2.9 on 2024-03-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_ondecomprar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ondecomprar',
            options={'verbose_name_plural': 'Onde Comprar'},
        ),
        migrations.AddField(
            model_name='produtofotos',
            name='tipo',
            field=models.CharField(choices=[('natura', 'In Natura'), ('assado', 'Assado')], default='assado', max_length=9),
            preserve_default=False,
        ),
    ]
